language: ruby
rvm:
- 2.0.0
- 2.3.3
- jruby-19mode
- rbx-2


before_script:
 - bundle install

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: 
 - bundle exec jekyll build

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based in