title: Cloud Foundry
description: > # this means to ignore newlines until "baseurl:"
  We built this city on DevOps and toil
baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
exclude: [test.md, todo.md, using.md, ideas, contributions.md, agenda.md]
# Build settings
markdown: kramdown

logo: "assets/img/icon.svg"

google_site_verification: googleXXXXXXXXXXXXXXXX.html


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/AAROC/foundry
  - title: comments-o
    url: http://discourse.sci-gaia.eu

# Build settings
markdown: kramdown
permalink: pretty